{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "counter-service.fullname" .) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
{{- with .Values.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
